apiVersion: v1
data:
  OPENAI_API_BASE: aHR0cHM6Ly9hcGkuZnVlbGl4LmFpL3Yx
  OPENAI_API_KEY: c2stM1BSVmdMd2RrVnpRNDhCNVhWalhxMg==
  OPENAI_MODEL: Y2xhdWRlLWhhaWt1LTQtNQ==
  POSTGRES_DB: ZGV2b3BzY29hY2g=
  POSTGRES_HOST: d2Fja29wcy1wcm9kLWRic2VydmVyLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  POSTGRES_PASSWORD: USg0KmEhXVFmLXZYaUs1Xw==
  POSTGRES_PORT: NTQzMg==
  POSTGRES_USER: d2Fja2FkbWlu
  REDIS_URL: cmVkaXM6Ly9yZWRpczo2Mzc5LzA=
  SECRET_KEY: cHJvZF9zZWNyZXRfa2V5X2Rldm9wc19jb2FjaF9zZWN1cmVfcmFuZG9t
  TAVILY_API_KEY: dHZseS1kZXYtdDBYZ1pranhncHpEdTIzbHZOT29ZOHJhUFVqZ3JtTUg=
kind: Secret
metadata:
  name: wackops-coach-secrets
  namespace: wackops-coach
